export const countryOptions = [
  { label: "Select Country...", value: "" },
  { label: "Ascension Island", value: "AC" },
  { label: "Andorra", value: "AD" },
  { label: "United Arab Emirates", value: "AE" },
  { label: "Afghanistan", value: "AF" },
  { label: "Antigua & Barbuda", value: "AG" },
  { label: "Anguilla", value: "AI" },
  { label: "Albania", value: "AL" },
  { label: "Armenia", value: "AM" },
  { label: "Netherlands Antilles", value: "AN" },
  { label: "Angola", value: "AO" },
  { label: "Argentina", value: "AR" },
  { label: "Austria", value: "AT" },
  { label: "Australia", value: "AU" },
  { label: "Aruba", value: "AW" },
  { label: "Åland Islands", value: "AX" },
  { label: "Azerbaijan", value: "AZ" },
  { label: "Bosnia & Herzegovina", value: "BA" },
  { label: "Barbados", value: "BB" },
  { label: "Bangladesh", value: "BD" },
  { label: "Belgium", value: "BE" },
  { label: "Burkina Faso", value: "BF" },
  { label: "Bulgaria", value: "BG" },
  { label: "Bahrain", value: "BH" },
  { label: "Burundi", value: "BI" },
  { label: "Benin", value: "BJ" },
  { label: "St. Barthélemy", value: "BL" },
  { label: "Bermuda", value: "BM" },
  { label: "Brunei", value: "BN" },
  { label: "Bolivia", value: "BO" },
  { label: "Caribbean Netherlands", value: "BQ" },
  { label: "Brazil", value: "BR" },
  { label: "Bahamas", value: "BS" },
  { label: "Bhutan", value: "BT" },
  { label: "Bouvet Island", value: "BV" },
  { label: "Botswana", value: "BW" },
  { label: "Belarus", value: "BY" },
  { label: "Belize", value: "BZ" },
  { label: "Canada", value: "CA" },
  { label: "Cocos (Keeling) Islands", value: "CC" },
  { label: "Congo - Kinshasa", value: "CD" },
  { label: "Central African Republic", value: "CF" },
  { label: "Congo - Brazzaville", value: "CG" },
  { label: "Switzerland", value: "CH" },
  { label: "Côte d’Ivoire", value: "CI" },
  { label: "Cook Islands", value: "CK" },
  { label: "Chile", value: "CL" },
  { label: "Cameroon", value: "CM" },
  { label: "China", value: "CN" },
  { label: "Colombia", value: "CO" },
  { label: "Costa Rica", value: "CR" },
  { label: "Cuba", value: "CU" },
  { label: "Cape Verde", value: "CV" },
  { label: "Curaçao", value: "CW" },
  { label: "Christmas Island", value: "CX" },
  { label: "Cyprus", value: "CY" },
  { label: "Czechia", value: "CZ" },
  { label: "Germany", value: "DE" },
  { label: "Djibouti", value: "DJ" },
  { label: "Denmark", value: "DK" },
  { label: "Dominica", value: "DM" },
  { label: "Dominican Republic", value: "DO" },
  { label: "Algeria", value: "DZ" },
  { label: "Ecuador", value: "EC" },
  { label: "Estonia", value: "EE" },
  { label: "Egypt", value: "EG" },
  { label: "Western Sahara", value: "EH" },
  { label: "Eritrea", value: "ER" },
  { label: "Spain", value: "ES" },
  { label: "Ethiopia", value: "ET" },
  { label: "Finland", value: "FI" },
  { label: "Fiji", value: "FJ" },
  { label: "Falkland Islands", value: "FK" },
  { label: "Faroe Islands", value: "FO" },
  { label: "France", value: "FR" },
  { label: "Gabon", value: "GA" },
  { label: "United Kingdom", value: "GB" },
  { label: "Grenada", value: "GD" },
  { label: "Georgia", value: "GE" },
  { label: "French Guiana", value: "GF" },
  { label: "Guernsey", value: "GG" },
  { label: "Ghana", value: "GH" },
  { label: "Gibraltar", value: "GI" },
  { label: "Greenland", value: "GL" },
  { label: "Gambia", value: "GM" },
  { label: "Guinea", value: "GN" },
  { label: "Guadeloupe", value: "GP" },
  { label: "Equatorial Guinea", value: "GQ" },
  { label: "Greece", value: "GR" },
  { label: "South Georgia & South Sandwich Islands", value: "GS" },
  { label: "Guatemala", value: "GT" },
  { label: "Guinea-Bissau", value: "GW" },
  { label: "Guyana", value: "GY" },
  { label: "Hong Kong SAR", value: "HK" },
  { label: "Heard & McDonald Islands", value: "HM" },
  { label: "Honduras", value: "HN" },
  { label: "Croatia", value: "HR" },
  { label: "Haiti", value: "HT" },
  { label: "Hungary", value: "HU" },
  { label: "Indonesia", value: "ID" },
  { label: "Ireland", value: "IE" },
  { label: "Israel", value: "IL" },
  { label: "Isle of Man", value: "IM" },
  { label: "India", value: "IN" },
  { label: "British Indian Ocean Territory", value: "IO" },
  { label: "Iraq", value: "IQ" },
  { label: "Iran", value: "IR" },
  { label: "Iceland", value: "IS" },
  { label: "Italy", value: "IT" },
  { label: "Jersey", value: "JE" },
  { label: "Jamaica", value: "JM" },
  { label: "Jordan", value: "JO" },
  { label: "Japan", value: "JP" },
  { label: "Kenya", value: "KE" },
  { label: "Kyrgyzstan", value: "KG" },
  { label: "Cambodia", value: "KH" },
  { label: "Kiribati", value: "KI" },
  { label: "Comoros", value: "KM" },
  { label: "St. Kitts & Nevis", value: "KN" },
  { label: "North Korea", value: "KP" },
  { label: "South Korea", value: "KR" },
  { label: "Kuwait", value: "KW" },
  { label: "Cayman Islands", value: "KY" },
  { label: "Kazakhstan", value: "KZ" },
  { label: "Laos", value: "LA" },
  { label: "Lebanon", value: "LB" },
  { label: "St. Lucia", value: "LC" },
  { label: "Liechtenstein", value: "LI" },
  { label: "Sri Lanka", value: "LK" },
  { label: "Liberia", value: "LR" },
  { label: "Lesotho", value: "LS" },
  { label: "Lithuania", value: "LT" },
  { label: "Luxembourg", value: "LU" },
  { label: "Latvia", value: "LV" },
  { label: "Libya", value: "LY" },
  { label: "Morocco", value: "MA" },
  { label: "Monaco", value: "MC" },
  { label: "Moldova", value: "MD" },
  { label: "Montenegro", value: "ME" },
  { label: "St. Martin", value: "MF" },
  { label: "Madagascar", value: "MG" },
  { label: "North Macedonia", value: "MK" },
  { label: "Mali", value: "ML" },
  { label: "Myanmar (Burma)", value: "MM" },
  { label: "Mongolia", value: "MN" },
  { label: "Macao SAR", value: "MO" },
  { label: "Martinique", value: "MQ" },
  { label: "Mauritania", value: "MR" },
  { label: "Montserrat", value: "MS" },
  { label: "Malta", value: "MT" },
  { label: "Mauritius", value: "MU" },
  { label: "Maldives", value: "MV" },
  { label: "Malawi", value: "MW" },
  { label: "Mexico", value: "MX" },
  { label: "Malaysia", value: "MY" },
  { label: "Mozambique", value: "MZ" },
  { label: "Namibia", value: "NA" },
  { label: "New Caledonia", value: "NC" },
  { label: "Niger", value: "NE" },
  { label: "Norfolk Island", value: "NF" },
  { label: "Nigeria", value: "NG" },
  { label: "Nicaragua", value: "NI" },
  { label: "Netherlands", value: "NL" },
  { label: "Norway", value: "NO" },
  { label: "Nepal", value: "NP" },
  { label: "Nauru", value: "NR" },
  { label: "Niue", value: "NU" },
  { label: "New Zealand", value: "NZ" },
  { label: "Oman", value: "OM" },
  { label: "Panama", value: "PA" },
  { label: "Peru", value: "PE" },
  { label: "French Polynesia", value: "PF" },
  { label: "Papua New Guinea", value: "PG" },
  { label: "Philippines", value: "PH" },
  { label: "Pakistan", value: "PK" },
  { label: "Poland", value: "PL" },
  { label: "St. Pierre & Miquelon", value: "PM" },
  { label: "Pitcairn Islands", value: "PN" },
  { label: "Palestinian Territories", value: "PS" },
  { label: "Portugal", value: "PT" },
  { label: "Paraguay", value: "PY" },
  { label: "Qatar", value: "QA" },
  { label: "Réunion", value: "RE" },
  { label: "Romania", value: "RO" },
  { label: "Serbia", value: "RS" },
  { label: "Russia", value: "RU" },
  { label: "Rwanda", value: "RW" },
  { label: "Saudi Arabia", value: "SA" },
  { label: "Solomon Islands", value: "SB" },
  { label: "Seychelles", value: "SC" },
  { label: "Sudan", value: "SD" },
  { label: "Sweden", value: "SE" },
  { label: "Singapore", value: "SG" },
  { label: "St. Helena", value: "SH" },
  { label: "Slovenia", value: "SI" },
  { label: "Svalbard & Jan Mayen", value: "SJ" },
  { label: "Slovakia", value: "SK" },
  { label: "Sierra Leone", value: "SL" },
  { label: "San Marino", value: "SM" },
  { label: "Senegal", value: "SN" },
  { label: "Somalia", value: "SO" },
  { label: "Suriname", value: "SR" },
  { label: "South Sudan", value: "SS" },
  { label: "São Tomé & Príncipe", value: "ST" },
  { label: "El Salvador", value: "SV" },
  { label: "Sint Maarten", value: "SX" },
  { label: "Syria", value: "SY" },
  { label: "Eswatini", value: "SZ" },
  { label: "Tristan da Cunha", value: "TA" },
  { label: "Turks & Caicos Islands", value: "TC" },
  { label: "Chad", value: "TD" },
  { label: "French Southern Territories", value: "TF" },
  { label: "Togo", value: "TG" },
  { label: "Thailand", value: "TH" },
  { label: "Tajikistan", value: "TJ" },
  { label: "Tokelau", value: "TK" },
  { label: "Timor-Leste", value: "TL" },
  { label: "Turkmenistan", value: "TM" },
  { label: "Tunisia", value: "TN" },
  { label: "Tonga", value: "TO" },
  { label: "Türkiye", value: "TR" },
  { label: "Trinidad & Tobago", value: "TT" },
  { label: "Tuvalu", value: "TV" },
  { label: "Taiwan", value: "TW" },
  { label: "Tanzania", value: "TZ" },
  { label: "Ukraine", value: "UA" },
  { label: "Uganda", value: "UG" },
  { label: "U.S. Outlying Islands", value: "UM" },
  { label: "United States", value: "US" },
  { label: "Uruguay", value: "UY" },
  { label: "Uzbekistan", value: "UZ" },
  { label: "Vatican City", value: "VA" },
  { label: "St. Vincent & Grenadines", value: "VC" },
  { label: "Venezuela", value: "VE" },
  { label: "British Virgin Islands", value: "VG" },
  { label: "Vietnam", value: "VN" },
  { label: "Vanuatu", value: "VU" },
  { label: "Wallis & Futuna", value: "WF" },
  { label: "Samoa", value: "WS" },
  { label: "Kosovo", value: "XK" },
  { label: "Yemen", value: "YE" },
  { label: "Mayotte", value: "YT" },
  { label: "South Africa", value: "ZA" },
  { label: "Zambia", value: "ZM" },
  { label: "Zimbabwe", value: "ZW" },
  { label: "Unknown Region", value: "ZZ" }
];

export const languageOptions = [
  { label: "Select Language...", value: "" },
  { label: "Afrikaans", value: "AF" },
  { label: "Akan", value: "AK" },
  { label: "Amharic", value: "AM" },
  { label: "Arabic", value: "AR" },
  { label: "Assamese", value: "AS" },
  { label: "Azerbaijani", value: "AZ" },
  { label: "Belarusian", value: "BE" },
  { label: "Bulgarian", value: "BG" },
  { label: "Bambara", value: "BM" },
  { label: "Bangla", value: "BN" },
  { label: "Tibetan", value: "BO" },
  { label: "Breton", value: "BR" },
  { label: "Bosnian", value: "BS" },
  { label: "Catalan", value: "CA" },
  { label: "Chechen", value: "CE" },
  { label: "Central Kurdish", value: "CKB" },
  { label: "Czech", value: "CS" },
  { label: "Church Slavic", value: "CU" },
  { label: "Welsh", value: "CY" },
  { label: "Danish", value: "DA" },
  { label: "German", value: "DE" },
  { label: "Dzongkha", value: "DZ" },
  { label: "Ewe", value: "EE" },
  { label: "Greek", value: "EL" },
  { label: "English", value: "EN" },
  { label: "Esperanto", value: "EO" },
  { label: "Spanish", value: "ES" },
  { label: "Estonian", value: "ET" },
  { label: "Basque", value: "EU" },
  { label: "Persian", value: "FA" },
  { label: "Fulah", value: "FF" },
  { label: "Finnish", value: "FI" },
  { label: "Filipino", value: "FIL" },
  { label: "Faroese", value: "FO" },
  { label: "French", value: "FR" },
  { label: "Western Frisian", value: "FY" },
  { label: "Irish", value: "GA" },
  { label: "Scottish Gaelic", value: "GD" },
  { label: "Galician", value: "GL" },
  { label: "Gujarati", value: "GU" },
  { label: "Manx", value: "GV" },
  { label: "Hausa", value: "HA" },
  { label: "Hebrew", value: "HE" },
  { label: "Hindi", value: "HI" },
  { label: "Croatian", value: "HR" },
  { label: "Hungarian", value: "HU" },
  { label: "Armenian", value: "HY" },
  { label: "Interlingua", value: "IA" },
  { label: "Indonesian", value: "ID" },
  { label: "Igbo", value: "IG" },
  { label: "Sichuan Yi", value: "II" },
  { label: "Icelandic", value: "IS" },
  { label: "Italian", value: "IT" },
  { label: "Japanese", value: "JA" },
  { label: "Javanese", value: "JV" },
  { label: "Georgian", value: "KA" },
  { label: "Kikuyu", value: "KI" },
  { label: "Kazakh", value: "KK" },
  { label: "Kalaallisut", value: "KL" },
  { label: "Khmer", value: "KM" },
  { label: "Kannada", value: "KN" },
  { label: "Korean", value: "KO" },
  { label: "Kashmiri", value: "KS" },
  { label: "Kurdish", value: "KU" },
  { label: "Cornish", value: "KW" },
  { label: "Kyrgyz", value: "KY" },
  { label: "Latin", value: "LA" },
  { label: "Luxembourgish", value: "LB" },
  { label: "Ganda", value: "LG" },
  { label: "Lingala", value: "LN" },
  { label: "Lao", value: "LO" },
  { label: "Lithuanian", value: "LT" },
  { label: "Luba-Katanga", value: "LU" },
  { label: "Latvian", value: "LV" },
  { label: "Malagasy", value: "MG" },
  { label: "Māori", value: "MI" },
  { label: "Macedonian", value: "MK" },
  { label: "Malayalam", value: "ML" },
  { label: "Mongolian", value: "MN" },
  { label: "Moldavian", value: "MO" },
  { label: "Marathi", value: "MR" },
  { label: "Malay", value: "MS" },
  { label: "Maltese", value: "MT" },
  { label: "Burmese", value: "MY" },
  { label: "Norwegian (Bokmål)", value: "NB" },
  { label: "North Ndebele", value: "ND" },
  { label: "Nepali", value: "NE" },
  { label: "Dutch", value: "NL" },
  { label: "Norwegian Nynorsk", value: "NN" },
  { label: "Norwegian", value: "NO" },
  { label: "Oromo", value: "OM" },
  { label: "Odia", value: "OR" },
  { label: "Ossetic", value: "OS" },
  { label: "Punjabi", value: "PA" },
  { label: "Polish", value: "PL" },
  { label: "Pashto", value: "PS" },
  { label: "Portuguese", value: "PT" },
  { label: "Portuguese (Brazil)", value: "PT_BR" },
  { label: "Portuguese (Portugal)", value: "PT_PT" },
  { label: "Quechua", value: "QU" },
  { label: "Romansh", value: "RM" },
  { label: "Rundi", value: "RN" },
  { label: "Romanian", value: "RO" },
  { label: "Russian", value: "RU" },
  { label: "Kinyarwanda", value: "RW" },
  { label: "Sanskrit", value: "SA" },
  { label: "Sardinian", value: "SC" },
  { label: "Sindhi", value: "SD" },
  { label: "Northern Sami", value: "SE" },
  { label: "Sango", value: "SG" },
  { label: "Serbo-Croatian", value: "SH" },
  { label: "Sinhala", value: "SI" },
  { label: "Slovak", value: "SK" },
  { label: "Slovenian", value: "SL" },
  { label: "Shona", value: "SN" },
  { label: "Somali", value: "SO" },
  { label: "Albanian", value: "SQ" },
  { label: "Serbian", value: "SR" },
  { label: "Sundanese", value: "SU" },
  { label: "Swedish", value: "SV" },
  { label: "Swahili", value: "SW" },
  { label: "Tamil", value: "TA" },
  { label: "Telugu", value: "TE" },
  { label: "Tajik", value: "TG" },
  { label: "Thai", value: "TH" },
  { label: "Tigrinya", value: "TI" },
  { label: "Turkmen", value: "TK" },
  { label: "Tongan", value: "TO" },
  { label: "Turkish", value: "TR" },
  { label: "Tatar", value: "TT" },
  { label: "Uyghur", value: "UG" },
  { label: "Ukrainian", value: "UK" },
  { label: "Urdu", value: "UR" },
  { label: "Uzbek", value: "UZ" },
  { label: "Vietnamese", value: "VI" },
  { label: "Volapük", value: "VO" },
  { label: "Wolof", value: "WO" },
  { label: "Xhosa", value: "XH" },
  { label: "Yiddish", value: "YI" },
  { label: "Yoruba", value: "YO" },
  { label: "Chinese", value: "ZH" },
  { label: "Chinese (Simplified)", value: "ZH_CN" },
  { label: "Chinese (Traditional)", value: "ZH_TW" },
  { label: "Zulu", value: "ZU" }
];