# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "6473332dff158d7aab8327543871590a"
name = "age-verification"
handle = "age-verification-58"
application_url = "https://softball-mysterious-it-uses.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "https://imaging-reproductive-new-members.trycloudflare.com/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "https://imaging-reproductive-new-members.trycloudflare.com/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""
optional_scopes = [
  "read_themes",
  "read_locales",
  "write_themes",
  "write_script_tags"
]

[auth]
redirect_urls = [
  "https://softball-mysterious-it-uses.trycloudflare.com/auth/callback",
  "https://softball-mysterious-it-uses.trycloudflare.com/auth/shopify/callback",
  "https://softball-mysterious-it-uses.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = true
