# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "6473332dff158d7aab8327543871590a"
name = "age-verification"
handle = "age-verification-58"
application_url = "https://gospel-blowing-cottages-pop.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "https://imaging-reproductive-new-members.trycloudflare.com/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "https://imaging-reproductive-new-members.trycloudflare.com/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "shop/update" ]
  uri = "https://imaging-reproductive-new-members.trycloudflare.com/webhooks/shop/update"

  [[webhooks.subscriptions]]
  topics = [ "themes/publish" ]
  uri = "https://imaging-reproductive-new-members.trycloudflare.com/webhooks/themes/publish"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_themes"
optional_scopes = [ "read_locales", "write_themes" ]

[auth]
redirect_urls = [
  "https://gospel-blowing-cottages-pop.trycloudflare.com/auth/callback",
  "https://gospel-blowing-cottages-pop.trycloudflare.com/auth/shopify/callback",
  "https://gospel-blowing-cottages-pop.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = true
